k8s_vms:
  master:
    vmid: 9101
    template_id: 9000
    name: k8s-master
    ip_cidr: 192.168.1.101/24
    gateway: 192.168.1.1
    cores: 4
    memory: 4096
    disk_size: "20G"
    bridge: vmbr0
    storage: local-lvm
