apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-ci
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-ci-admin-binding
subjects:
  - kind: ServiceAccount
    name: gitlab-ci
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io