---
- name: Read MicroK8s CA Certificate
  slurp:
    src: /var/snap/microk8s/current/certs/ca.crt
  register: ca_cert_raw
  become: yes

- name: Decode CA cert and export
  set_fact:
    k8s_ca_crt_b64: "{{ ca_cert_raw['content'] }}"

- name: Generate kubeconfig with embedded token from template
  template:
    src: kubeconfig.yml.j2
    dest: /tmp/kubeconfig

- name: Encode kubeconfig in base64
  shell: cat /tmp/kubeconfig | base64 -w0
  register: kubeconfig_b64
  changed_when: false
  delegate_to: localhost