---
galaxy_info:
  author: RAPHTER1
  description: Install and configure MicroK8s on Ubuntu
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
