apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  source:
    repoURL: https://gitlab.com/dst-eshop/eshop-infrastructure.git
    targetRevision: main
    path: argocd/apps               # <– dossier où vivent tous les enfants
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
