---
- name: Creer un user ansible
  become: true
  ansible.builtin.user:
    name: ansible
    shell: /bin/bash
    create_home: yes
    group: sudo
    append: yes

- name: Ajouter la clé SSH publique à l'utilisateur ansible
  ansible.builtin.authorized_key:
    user: ansible
    key: "{{ lookup('env', 'K8S_PROXMOX_PUBLIC_KEY') | default('~/.ssh/id_rsa.pub')), true) }}"
