- name: Fail if GitLab API token is not defined
  fail:
    msg: "GITLAB_API_TOKEN is not set. Please export it in your .env.local or CI/CD variables."
  when: lookup('env', 'GITLAB_API_TOKEN') is not defined
  delegate_to: localhost

- name: Apply Gitlab CI ServiceAccount manifest
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/files/gitlab_sa.yaml"
    kubeconfig: /home/ubuntu/.kube/config
    context: microk8s
  become: true

- name: Get GitLab CI SA token
  shell: >
    microk8s kubectl -n kube-system get secret \
    -o jsonpath="{.items[?(@.metadata.annotations['kubernetes\.io/service-account\.name']=='gitlab-ci')].data.token}" | base64 -d
  register: gitlab_ci_sa_token
  become: true
  no_log: true

- name: Debug token (only if DEBUG=true)
  debug:
    msg: "GitLab CI token: {{ gitlab_ci_sa_token.stdout }}"
  when: lookup('env', 'DEBUG') == 'true'

- name: Read MicroK8s CA Certificate
  slurp:
    src: /var/snap/microk8s/current/certs/ca.crt
  register: ca_cert_raw
  become: true

- name: Decode CA cert and export
  set_fact:
    k8s_ca_cert_b64: "{{ ca_cert_raw['content'] }}"

- name: Render new GitLab kubeconfig content locally
  template:
    src: kubeconfig_gitlab.yml.j2
  register: rendered_kubeconfig
  vars:
    k8s_api_public_url: "{{ lookup('env', 'K8S_API_PUBLIC_URL') }}"
    gitlab_ci_sa_token: "{{ gitlab_ci_sa_token.stdout }}"
    k8s_ca_crt_b64: "{{ k8s_ca_cert_b64 }}"
  delegate_to: localhost
  check_mode: true  # ne fait rien, juste pour rendre output.content disponible
  changed_when: false

- name: Write kubeconfig to /tmp
  copy:
    content: "{{ rendered_kubeconfig.content }}"
    dest: /tmp/kubeconfig_gitlab.yml
    mode: '0600'
  become: true

- name: Encode GitLab Kubeconfig in base64
  shell: base64 -w0 /tmp/kubeconfig_gitlab.yml
  register: kubeconfig_gitlab_b64
  changed_when: false
  become: true

- name: Get existing GitLab variable KUBECONFIG_GITLAB_B64
  uri:
    url: "https://gitlab.com/api/v4/projects/{{ lookup('env', 'CI_PROJECT_ID') }}/variables/KUBECONFIG_GITLAB_B64"
    method: GET
    headers:
      PRIVATE_TOKEN: "{{ lookup('env', 'GITLAB_API_TOKEN') }}"
  register: existing_gitlab_var
  failed_when: false
  delegate_to: localhost

- name: Debug GitLab kubeconfig value (if DEBUG=true)
  debug:
    msg: "Current GitLab var: {{ existing_gitlab_var.json.value }}"
  when: lookup('env', 'DEBUG') == 'true' and existing_gitlab_var.status == 200

- name: Push GitLab kubeconfig as project variable via GitLab API (only if changed)
  uri:
    url: "https://gitlab.com/api/v4/projects/{{ lookup('env', 'CI_PROJECT_ID') }}/variables/KUBECONFIG_GITLAB_B64"
    method: PUT
    headers:
      PRIVATE-TOKEN: "{{ lookup('env', 'GITLAB_API_TOKEN') }}"
    body_format: form-urlencoded
    body:
      value: "{{ kubeconfig_gitlab_b64.stdout }}"
      masked: "false"
      protected: "false"
    status_code: 200
  when: existing_gitlab_var.status != 200 or existing_gitlab_var.json.value != kubeconfig_gitlab_b64.stdout
  delegate_to: localhost