all:
  hosts:
    proxmox_host:
      ansible_host: "{{ lookup('env', 'PROXMOX_HOST_IP') }}"
      ansible_user: ansible
      ansible_port: 9000
      ansible_ssh_private_key_file: ~/.ssh/ansible_proxmox
      ansible_python_interpreter: /usr/bin/python3

    k8s-proxmox:
      ansible_host: "{{ lookup('env', 'PROXMOX_HOST_IP') }}"
      ansible_user: ubuntu
      ansible_port: 9101
      ansible_ssh_private_key_file: ~/.ssh/K8s_proxmox
      ansible_python_interpreter: /usr/bin/python3

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
