all:
  children:
    provision:
      hosts:
        proxmox_host:
          ansible_host: "$PROXMOX_HOST_IP"
          ansible_user: ansible
          ansible_port: "$PROXMOX_HOST_PORT"
          ansible_ssh_private_key_file: "$ANSIBLE_PROXMOX_SSH_PRIVATE_KEY_FILE"

          ansible_python_interpreter: /usr/bin/python3
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
