all:
  hosts:
    proxmox-host:
      ansible_host: $PROXMOX_HOST_IP
      ansible_user: ansible
      ansible_port: 9000
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3

    k8s-proxmox:
      ansible_host: $PROXMOX_HOST_IP
      ansible_user: ansible
      ansible_port: 9101
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
