# Étape 1 : Provisionner les VMs depuis le hôte Proxmox
- name: Provisionner les VMs sur Proxmox
  hosts: proxmox_host
  gather_facts: false
  tasks:
    - name: DEBUG - Vérifier la variable
      debug:
        var: k8s_vms

    - name: Provisionner chaque VM
      include_role:
        name: proxmox_vm_manage
      loop: "{{ query('dict', k8s_vms) }}"
      loop_control:
        label: "{{ item.key }}"
      vars:
        vm_cfg: "{{ item.value }}"

# Étape 2 : Installer MicroK8s sur le nœud master
- name: Installer et configurer MicroK8s
  hosts: k8s_master
  become: true
  roles:
    - setup_microk8s
