- name: Vérifier si la VM existe déjà
  become: true
  shell: |
    /usr/sbin/qm list | awk '{print $1}' | grep -q '^{{ item.key }}$'
  register: vm_present
  changed_when: false
  failed_when: false

# ——————————————————————————————————
#  On importe le bon sous-fichier :
# ——————————————————————————————————
- import_tasks: create.yml
  when: vm_present.rc != 0            # ← VM absente → on la crée

- import_tasks: skip.yml
  when: vm_present.rc == 0            # ← VM déjà là → on ne touche à rien
